# costmap_common_params.yaml --- 
# 
# Filename: costmap_common_params.yaml
# Description: Global parameters for layered costmap
# Created: Tue Nov 24 14:33:55 2015 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:
robot_radius: 0.22
footprint: [[0.35, 0.0], [0.2009800006813722, 0.08948206147667603], [0.14720873339894883, 0.1634918616050267], [0.06798373876248844, 0.2092324335849338], [-0.022996261918883733, 0.21879481698102016], [-0.10999999999999995, 0.1905255888325765], [-0.1779837387624884, 0.12931275550434412], [-0.21519247216143722, 0.04574057197990714], [-0.21519247216143725, -0.045740571979906997], [-0.17798373876248846, -0.12931275550434407], [-0.1100000000000001, -0.19052558883257645], [-0.02299626191888393, -0.21879481698102013], [0.10815594803123152, -0.33286978070330375], [0.2341957122256002, -0.2601006889170881], [0.3197409101749102, -0.1423578250765303]]

# costmap_2d plugins declaration.
plugins:
  - {name: map_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer, type: "squirrel_navigation::DownprojectionLayer"}
  - {name: inflation_layer, type: "squirrel_navigation::InflationLayer"}

# Parameters for squirrel_navigation::MapLayer, if using costmap_2d::StaticLayer, there lines are ignored
map_layer:
  robot_link_radius: 0.22
  inflation_radius: 0.6
  cost_scaling_factor: 10.0

# Parameters for squirrel_navigation::DownprojectionLayer
obstacles_layer:
  obstacle_range: 5.0
  raytrace_range: 10.0 
  observation_sources: laser_scan rgbd_scan
  rgbd_scan: {sensor_frame: kinect_depth_optical_frame, data_type: PointCloud2, topic: rgbdscan, marking: true, clearing: true}
  laser_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: true} 
  publish_voxel_map: true
  min_obstacle_height: -0.03
  robot_height: 0.9
  floor_threshold: 0.03
  footprint/enabled: true

# Parameters for squirrel_navigation::InflationLayer
inflation_layer:
  inscribed_radius: 0.22
  inscribed_radius_from_footprint: false
  inflation_radius: 0.6,
  cost_scaling_factor: 10.0,

#
# costmap_common_params.yaml ends here
