# joint handles
kinect_tilt_joint: 
  use_navigation_angle: false  
  navigation_angle: 0.6
  command_topic: /tilt_controller/command 
  state_topic: /tilt_controller/joint_state
kinect_pan_joint: 
  use_navigation_angle: false
  command_topic: /pan_controller/command 
  state_topic: /pan_controller/joint_state
